"""
learning_core.py — shared library for the Learning Library.

Storage model: one Markdown file per item under learning/, exactly like the
people/ and projects/ collections. Each learning/<id>.md is a YAML-style
front-matter block (the structured fields) followed by a free-text body (the
blurb). This module is the read/write/validate layer the learning.py CLI sits
on; keeping it pure and separate mirrors how radar_core backs radar.py.

The Markdown files are the source of truth. build_learning.py aggregates them
into data/learning.json, which the web page (web/learning.jsx) reads — the same
build-step contract projects/ and people/ use. The learning.py CLI writes the
Markdown *and* refreshes learning.json, so a CLI edit still publishes
immediately; a hand-edit to a .md just needs `python build_learning.py`.

Every item carries a `type` (book · article · video · certification), a
consumption `status`, curated `topics`, and a `rating`. Type-specific
"length" fields differ (books: pages/pages_read, articles: minutes, videos:
duration, certifications: price) — new_item builds the right key set per type
so each card renders correctly.
"""

import glob
import json
import os
import re
from datetime import date

# --- paths -------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
LEARNING_DIR = os.path.join(HERE, "learning")     # source of truth: one .md per item
LEARNING_JSON = os.path.join(DATA_DIR, "learning.json")  # generated by build_learning.py

# --- vocabulary --------------------------------------------------------
TYPES = ["book", "article", "video", "certification"]

# Consumption pipeline, ordered most-resolved first — the same convention
# the tech radar uses for rings (Adopted → … → Archived). Read sits innermost
# (done), Shelved furthest out (a deliberate "not now" set-aside).
STATUS_ORDER = ["Read", "Reading", "Queued", "Discovered", "Shelved"]

# The date field each status stamps when an item enters it. Mirrors how the
# radar stamps archived_at on entry to Archived: set on the way in (preserving
# an existing stamp), and `shelved` is cleared on the way back out.
STATUS_DATE_FIELD = {
    "Discovered": "added",
    "Queued": "queued",
    "Reading": "started",
    "Read": "finished",
    "Shelved": "shelved",
}

# Curated topic vocabulary — the SAME set the tech radar uses (minus the two
# scraper-only OCR/Data-Feeds extras the radar added), so a book and a
# technology can share a topic. Kept in sync with TOPICS in web/learning.jsx.
TOPICS = ["AI", "ML", "Agents", "Skills", "Prompts",
          "Trading", "Quant", "RAG", "Data Feeds"]

# The type-specific "length" field(s) each content type carries.
TYPE_LENGTH_FIELDS = {
    "book": ["pages", "pages_read"],
    "article": ["minutes"],
    "video": ["duration"],
    "certification": ["price"],
}


def normalize_topics(values):
    """Validate/canonicalize an iterable of topic strings against TOPICS.

    Case-insensitive ('agents' -> 'Agents'); order preserved, duplicates
    dropped. Returns (kept, unknown) so callers can report rejects. A falsy
    input yields ([], []). Identical contract to radar_core.normalize_topics."""
    if not values:
        return [], []
    by_lower = {t.lower(): t for t in TOPICS}
    kept, unknown, seen = [], [], set()
    for v in values:
        canon = by_lower.get(str(v).strip().lower())
        if canon is None:
            unknown.append(v)
        elif canon not in seen:
            seen.add(canon)
            kept.append(canon)
    return kept, unknown


# --- id helpers --------------------------------------------------------
def slugify(text):
    """Human-readable id slug from a title, e.g. 'Team Topologies' ->
    'team-topologies'. Kept short and hyphenated to match existing ids."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text or "").strip("-").lower()
    return slug[:60] or "item"


def unique_id(base, existing_ids):
    """Return `base`, or base-2, base-3, … so it doesn't collide with an
    id already in the library."""
    if base not in existing_ids:
        return base
    n = 2
    while f"{base}-{n}" in existing_ids:
        n += 1
    return f"{base}-{n}"


# --- Markdown front-matter (parse) -------------------------------------
def _as_list(v):
    if v is None:
        return []
    return v if isinstance(v, list) else [v]


def _int_or_none(v):
    """Coerce a front-matter scalar to int, or None for blank/None."""
    if v in (None, ""):
        return None
    try:
        return int(str(v).strip())
    except (TypeError, ValueError):
        return None


def _parse_scalar(raw):
    """Strip a matching pair of surrounding quotes and whitespace; '' -> None."""
    v = raw.strip()
    if len(v) >= 2 and v[0] in "\"'" and v[-1] == v[0]:
        v = v[1:-1]
    return v or None


def _parse_inline_list(raw):
    """[a, b, "c d"] -> ['a', 'b', 'c d']. Empty / '[]' -> []."""
    inner = raw.strip()
    if inner.startswith("["):
        inner = inner[1:]
    if inner.endswith("]"):
        inner = inner[:-1]
    return [x for x in (_parse_scalar(p) for p in inner.split(",")) if x]


def parse_front_matter(text):
    """Split a Markdown file into (front_matter_dict, body_string).

    Recognises a leading `---` fenced block. Inside it:
      key: value        -> scalar (None if blank)
      key: [a, b, c]     -> inline list
      key:               -> followed by `- item` lines -> block list
    Anything after the closing fence is the body. Mirrors the parser in
    build_projects.py so the three Markdown-backed collections read alike."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text.strip()

    fm = {}
    i, pending_key, end = 1, None, None
    while i < len(lines):
        stripped = lines[i].strip()
        if stripped == "---":
            end = i
            break
        if pending_key is not None and stripped.startswith("- "):
            val = _parse_scalar(stripped[2:])
            if val:
                if not isinstance(fm.get(pending_key), list):
                    fm[pending_key] = []
                fm[pending_key].append(val)
            i += 1
            continue
        pending_key = None
        if not stripped or stripped.startswith("#"):
            i += 1
            continue
        if ":" in stripped:
            key, _, rest = stripped.partition(":")
            key, rest = key.strip(), rest.strip()
            if rest.startswith("["):
                fm[key] = _parse_inline_list(rest)
            elif rest == "":
                fm[key] = None
                pending_key = key
            else:
                fm[key] = _parse_scalar(rest)
        i += 1

    body = "\n".join(lines[end + 1:]).strip() if end is not None else ""
    return fm, body


def to_item(fm, body, default_id):
    """Build a canonical item dict from parsed front-matter + body. Emits the
    exact key set/order new_item does per type, so a round-trip through Markdown
    is stable and data/learning.json keeps the shape the web page expects. The
    body is the blurb."""
    item_type = fm.get("type") or "book"
    item = {
        "id": fm.get("id") or default_id,
        "type": item_type,
        "title": fm.get("title") or "",
        "author": fm.get("author") or "",
    }
    if item_type != "book":
        item["source"] = fm.get("source") or ""
        item["url"] = fm.get("url") or ""
    if item_type == "certification":
        item["price"] = fm.get("price")
    item["year"] = _int_or_none(fm.get("year"))
    item["status"] = fm.get("status") or "Discovered"
    item["topics"] = normalize_topics(_as_list(fm.get("topics")))[0]
    if item_type == "book":
        item["pages"] = _int_or_none(fm.get("pages"))
        item["pages_read"] = _int_or_none(fm.get("pages_read"))
    elif item_type == "article":
        item["minutes"] = _int_or_none(fm.get("minutes"))
    elif item_type == "video":
        item["duration"] = fm.get("duration") or None
    item["rating"] = _int_or_none(fm.get("rating"))
    for f in ("added", "started", "queued", "finished", "shelved"):
        item[f] = fm.get(f) or None
    if fm.get("shelved_note"):
        item["shelved_note"] = fm.get("shelved_note")
    item["blurb"] = (body or "").strip()
    return item


# --- Markdown front-matter (serialize) ---------------------------------
def _fmt_scalar(s):
    """Render a string front-matter value, quoting only when a bare value would
    be misread (empty, leading `[`/quote, or edge whitespace)."""
    if s == "":
        return ""
    needs_quote = s != s.strip() or s[0] in "[\"'"
    if not needs_quote:
        return s
    if '"' not in s:
        return f'"{s}"'
    if "'" not in s:
        return f"'{s}'"
    return '"' + s.replace('"', "'") + '"'


def _fmt(value):
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_fmt_scalar(str(v)) for v in value) + "]"
    return _fmt_scalar(str(value))


def serialize_item(item):
    """Render an item to Markdown: every field except `blurb` becomes a
    front-matter line (in the item's canonical order); `blurb` becomes the
    body. None-valued fields are written as an empty `key:` so a hand-editor
    sees the full, fillable field set."""
    lines = ["---"]
    for key, value in item.items():
        if key == "blurb":
            continue
        lines.append(f"{key}: {_fmt(value)}".rstrip())
    lines += ["---", "", (item.get("blurb") or "").strip(), ""]
    return "\n".join(lines)


# --- read / write ------------------------------------------------------
def item_path(item_id):
    return os.path.join(LEARNING_DIR, f"{item_id}.md")


def load_items():
    """Parse every learning/*.md (except README.md) into canonical item dicts,
    ordered by filename for a stable, deterministic aggregate."""
    out = []
    if not os.path.isdir(LEARNING_DIR):
        return out
    for path in sorted(glob.glob(os.path.join(LEARNING_DIR, "*.md"))):
        if os.path.basename(path).lower() == "readme.md":
            continue
        with open(path, encoding="utf-8") as f:
            fm, body = parse_front_matter(f.read())
        default_id = os.path.splitext(os.path.basename(path))[0]
        out.append(to_item(fm, body, default_id))
    return out


def load():
    """The whole collection as {generated, items} — the same envelope the CLI
    worked with when the store was a single JSON file."""
    return {"generated": date.today().isoformat(), "items": load_items()}


def save_item(item):
    """Write one item to its learning/<id>.md, skipping the write when the
    on-disk bytes already match (no needless git churn)."""
    os.makedirs(LEARNING_DIR, exist_ok=True)
    text = serialize_item(item)
    path = item_path(item["id"])
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            if f.read() == text:
                return path
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return path


def save(doc, day=None):
    """Persist every item in the document to its Markdown file. Writing the
    Markdown is the source-of-truth write; refreshing data/learning.json is a
    separate build step (build_learning.py), which the CLI runs for you."""
    items = doc.get("items", [])
    for item in items:
        save_item(item)
    return len(items)


def resolve(items, needle):
    """Find one item by exact id, exact title, or unique partial title
    (case-insensitive). Returns (item, None) on success or (None, message)
    describing the miss/ambiguity — the CLI turns that into an exit."""
    n = (needle or "").lower()
    for it in items:
        if it.get("id", "").lower() == n:
            return it, None
    exact = [it for it in items if it.get("title", "").lower() == n]
    if len(exact) == 1:
        return exact[0], None
    partial = [it for it in items if n in it.get("title", "").lower()]
    if len(partial) == 1:
        return partial[0], None
    if len(partial) > 1:
        names = ", ".join(p.get("title", p.get("id", "?")) for p in partial)
        return None, f"ambiguous '{needle}' — matches: {names}"
    return None, f"no item matches '{needle}'"


# --- the item schema ---------------------------------------------------
def new_item(item_type, title, author=None, topics=None, year=None,
             blurb=None, url=None, source=None, status="Discovered",
             pages=None, minutes=None, duration=None, price=None,
             existing_ids=None):
    """Build a fresh Learning Library item with the exact key set the web
    page expects for its type. Shared fields come first; type-specific
    length/url/source fields are added per TYPES. The status's date stamp
    (e.g. `added` for Discovered) is set to today."""
    if item_type not in TYPES:
        raise ValueError(f"type must be one of: {', '.join(TYPES)}")
    if status not in STATUS_ORDER:
        raise ValueError(f"status must be one of: {', '.join(STATUS_ORDER)}")
    kept, _ = normalize_topics(topics)
    base = slugify(title)
    item_id = unique_id(base, set(existing_ids or []))

    item = {
        "id": item_id,
        "type": item_type,
        "title": title,
        "author": author or "",
    }
    # articles, videos and certifications carry a source + url; books don't.
    if item_type != "book":
        item["source"] = source or ""
        item["url"] = url or ""
    # certifications list price right after source/url (matches existing data)
    if item_type == "certification":
        item["price"] = price
    item["year"] = int(year) if year not in (None, "") else None
    item["status"] = status
    item["topics"] = kept
    # type-specific length fields
    if item_type == "book":
        item["pages"] = int(pages) if pages not in (None, "") else None
        item["pages_read"] = None
    elif item_type == "article":
        item["minutes"] = int(minutes) if minutes not in (None, "") else None
    elif item_type == "video":
        item["duration"] = duration or None
    # shared consumption/metadata fields
    item["rating"] = None
    for f in ("added", "started", "queued", "finished", "shelved"):
        item[f] = None
    item[STATUS_DATE_FIELD[status]] = date.today().isoformat()
    item["blurb"] = blurb or ""
    return item


def set_status(item, status, day=None):
    """Move an item to a consumption status, stamping the matching date
    field (preserving an existing stamp) and clearing the `shelved` stamp +
    note when leaving Shelved — the mirror of radar_core clearing archived_at
    on the way out of Archived."""
    if status not in STATUS_ORDER:
        raise ValueError(f"status must be one of: {', '.join(STATUS_ORDER)}")
    today = day or date.today().isoformat()
    if item.get("status") == "Shelved" and status != "Shelved":
        item["shelved"] = None
        item.pop("shelved_note", None)
    field = STATUS_DATE_FIELD[status]
    if not item.get(field):
        item[field] = today
    item["status"] = status
    return item
